# Run tests and integration tests on Windows, which are triggered by each master push.
# Currently, Python3.9 is only used as an environment.
# This is mainly for the sake of speed.
name: windows-tests

on:
  push:
    branches:
      - master
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-integration-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Setup cache
      uses: actions/cache@v3
      env:
        cache-name: windows-test-integration
      with:
        path: ~\\AppData\\Local\\pip\\Cache
        key: ${{ runner.os }}-3.9-${{ env.cache-name }}-${{ hashFiles('**/pyproject.toml') }}-v1
        restore-keys: |
          ${{ runner.os }}-3.9-${{ env.cache-name }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: "msmpi"

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off .
        python -c 'import optuna'
        optuna --version
        pip install --progress-bar off .[test]
        pip install --progress-bar off .[optional]
        pip install --progress-bar off .[integration]
        pip install "distributed<2023.3.2"

        # TODO(nabenabe0928): Remove the version constraint on Torch.
        # pip install "torch<2.2.0"
        pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
        pip install lightning

    - name: Output installed packages
      run: |
        pip freeze --all
    - name: Output dependency tree
      run: |
        pip install pipdeptree
        pipdeptree

    - name: Tests
      # Skip allennlp tests since it's not supported on Windows.
      run: |
        python -m pytest tests/integration_tests/test_pytorch_lightning.py
      env:
        OMP_NUM_THREADS: 1
